/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewGame.java
 *
 * Created on 23.4.2009, 11:17:10
 */

package com.ukkosnetti.gladius.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

import com.ukkosnetti.gladius.controller.Controller;
import com.ukkosnetti.gladius.gui.components.RedButton;

/**
 *
 * @author Humakt83
 */
public class NewGameView extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4982148463518448182L;
	private ImageIcon gladius = new ImageIcon("Gladius.png");

	/** Creates new form NewGame */
	public NewGameView(Controller c) {
		initComponents();
		Start.setActionCommand("START_NEW_GAME");
		Start.addActionListener(c);
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frameSize = getSize();
		if (frameSize.height > screenSize.height) {
			frameSize.height = screenSize.height;
		}
		if (frameSize.width > screenSize.width) {
			frameSize.width = screenSize.width;
		}
		// center frame to screen
		setLocation((screenSize.width - frameSize.width) / 3, (screenSize.height - frameSize.height) / 4);
		pack();
		setResizable(false);
		this.setIconImage(gladius.getImage());
		setVisible(true);
		// this.toFront();
	}

	public List<String> getTeamNames() {
		List<String> teamNames = new ArrayList<>(Arrays.asList(Team1.getText(), Team2.getText(), Team3.getText(), Team4.getText()));
		teamNames.removeAll(Collections.singleton(null));
		teamNames.removeAll(Collections.singleton(""));
		return teamNames;
	}

	public void disposeThis() {
		this.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		container = new JPanel() {
			private static final long serialVersionUID = 8767242190400775227L;

			public void paintComponent(Graphics g) {
				Graphics2D g2d = (Graphics2D) g;
				Dimension d = this.getSize();
				g2d.setPaint(new GradientPaint(0, 0, new Color(105, 0, 155), 50, 50, new Color(75, 0, 105), true));
				g2d.fillRect(0, 0, d.width, d.height);
			}
		};
		Start = new RedButton();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel2 = new javax.swing.JPanel() {
			private static final long serialVersionUID = 6711150594697216279L;

			public void paintComponent(Graphics g) {
				Graphics2D g2d = (Graphics2D) g;
				Dimension d = this.getSize();
				g2d.setPaint(new GradientPaint(0, 0, new Color(0, 0, 155), d.width, 0, new Color(0, 0, 85)));
				g2d.fillRect(0, 0, d.width, d.height);
			}
		};
		Team1 = new javax.swing.JTextField();
		Team2 = new javax.swing.JTextField();
		Team3 = new javax.swing.JTextField();
		Team4 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Let New Glorious Gladiator Battles In Höböttilandia Begin");

		Start.setText("START");

		jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setFont(new java.awt.Font("High Tower Text", 2, 13)); // NOI18N
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1
				.setText("Welcome mighty gladiator to Höböttilandia. A sparkling land of gold and riches, where all weird and strange races roam freely, \nincluding, but not limited to, beholders and \nhöböts. \n\nThe best and only way for all these races to \nmake livelihood and get entertainment, is \neither to be a gladiator or manager.");
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
		jPanel2.setToolTipText("Teams with no names will be computer controlled.");

		Team1.setToolTipText("Teams with no names will be computer controlled.");

		Team2.setToolTipText("Teams with no names will be computer controlled.");

		Team3.setToolTipText("Teams with no names will be computer controlled.");

		Team4.setToolTipText("Teams with no names will be computer controlled.");

		jLabel1.setText("Team 1");

		jLabel2.setText("Team 2");

		jLabel3.setText("Team 3");

		jLabel4.setText("Team 4");

		jLabel5.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
		jLabel5.setText("Teams");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1).addComponent(jLabel2)
																		.addComponent(jLabel3).addComponent(jLabel4))
														.addGap(14, 14, 14)
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(Team4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
																		.addComponent(Team3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
																		.addComponent(Team1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
																		.addComponent(Team2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)).addContainerGap())
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(jLabel5).addGap(57, 57, 57)))));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel2Layout
								.createSequentialGroup()
								.addComponent(jLabel5)
								.addGap(9, 9, 9)
								.addGroup(
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel1)
												.addComponent(Team1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Team2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel3)
												.addComponent(Team3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(12, 12, 12)
								.addGroup(
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
												.addComponent(Team4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(23, 23, 23)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(container);
		container.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup()
														.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap())
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(Start).addGap(181, 181, 181)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(Start).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		Start.setBackground(Color.RED);
		Start.setForeground(Color.WHITE);
		this.add(container);
		this.setBackground(Color.BLUE);
		this.setForeground(Color.RED);
		jPanel1.setBackground(Color.BLUE);
		jPanel2.setBackground(Color.BLUE);
		jScrollPane1.setBackground(Color.BLUE);
		jLabel1.setForeground(Color.WHITE);
		jLabel2.setForeground(Color.WHITE);
		jLabel3.setForeground(Color.WHITE);
		jLabel4.setForeground(Color.WHITE);
		jLabel5.setForeground(Color.WHITE);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Start;
	private javax.swing.JTextField Team1;
	private javax.swing.JTextField Team2;
	private javax.swing.JTextField Team3;
	private javax.swing.JTextField Team4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel container;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}
