/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on 14.4.2009, 16:18:48
 */

package com.ukkosnetti.gladius.gui;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.JLabel;
import javax.swing.JPanel;

import com.ukkosnetti.gladius.controller.Controller;
import com.ukkosnetti.gladius.gui.components.GradientPanel;
import com.ukkosnetti.gladius.gui.components.RedButton;

/**
 *
 * @author Humakt83
 */
public class MainPanel extends GradientPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3415582722735878738L;

	/** Creates new form MainPanel */
	public MainPanel() {
		initComponents();
	}

	public void setController(Controller c) {
		Tavern.setActionCommand("TAVERN");
		Tavern.addActionListener(c);
		Blacksmith.setActionCommand("BLACKSMITH");
		Blacksmith.addActionListener(c);
		StartBattle.setActionCommand("STARTBATTLE");
		StartBattle.addActionListener(c);
		SeasonBut.setActionCommand("SEASON");
		SeasonBut.addActionListener(c);
		TeamBut.addActionListener(c);
		TeamBut.setActionCommand("OTHERTEAMS");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		StartBattle = new RedButton();
		Tavern = new RedButton();
		Blacksmith = new RedButton();
		SeasonBut = new RedButton();
		TeamBut = new RedButton();
		curseas = new JLabel("SEASON ### ASW");
		container = new JPanel();
		setPreferredSize(new java.awt.Dimension(412, 333));
		curseas.setFont(new Font("Magneto", 1, 24));
		curseas.setForeground(Color.WHITE);
		StartBattle.setText("BATTLE");
		Tavern.setText("TAVERN");

		Blacksmith.setText("SHOP");

		Blacksmith.setEnabled(false);
		StartBattle.setEnabled(false);
		Tavern.setEnabled(false);
		SeasonBut.setText("SEASON");
		SeasonBut.setEnabled(false);

		TeamBut.setText("TEAMS");
		TeamBut.setEnabled(false);
		this.setLayout(new FlowLayout(FlowLayout.CENTER));
		this.add(curseas);
		this.add(container);
		container.setOpaque(false);
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(container);
		container.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(67, 67, 67)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(
												layout.createSequentialGroup()
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup().addGap(100, 100, 100).addComponent(StartBattle)).addComponent(Tavern))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(Blacksmith))
										.addGroup(
												layout.createSequentialGroup().addComponent(TeamBut)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(SeasonBut))).addContainerGap(82, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup().addGap(33, 33, 33).addComponent(StartBattle).addGap(81, 81, 81)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(TeamBut).addComponent(SeasonBut)))
										.addGroup(
												layout.createSequentialGroup().addGap(89, 89, 89)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(Blacksmith).addComponent(Tavern))))
						.addContainerGap(124, Short.MAX_VALUE)));
		Blacksmith.setBackground(Color.RED);
		Blacksmith.setForeground(Color.WHITE);
		StartBattle.setBackground(Color.RED);
		StartBattle.setForeground(Color.WHITE);
		Tavern.setBackground(Color.RED);
		Tavern.setForeground(Color.WHITE);
		SeasonBut.setBackground(Color.RED);
		SeasonBut.setForeground(Color.WHITE);
		TeamBut.setBackground(Color.RED);
		TeamBut.setForeground(Color.WHITE);
	}// </editor-fold>//GEN-END:initComponents

	public void enableStuff() {
		Blacksmith.setEnabled(true);
		StartBattle.setEnabled(true);
		Tavern.setEnabled(true);
		SeasonBut.setEnabled(true);
		TeamBut.setEnabled(true);
	}

	public void setSeason(int i) {
		curseas.setText("SEASON " + i + " ASW");
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Blacksmith;
	private javax.swing.JButton StartBattle;
	private javax.swing.JButton Tavern;
	private javax.swing.JButton SeasonBut;
	private javax.swing.JButton TeamBut;
	private JPanel container;
	private JLabel curseas;
	// End of variables declaration//GEN-END:variables
}